!
!  mod_OCT.f90
!
!  Free-Format Fortran Source File 
!  Generated by PGI Visual Fortran(R)
!  12/25/2012 3:19:01 PM
!

!use mod_OCT ,only: a,b
module mod_OCT
implicit none

complex*16,dimension(6,0:800020)::sai_t,khy_t,m_s_target

complex*16,dimension(6)::sai_,sai1_,sai0_,khy0_,khy1_,khy_,ct_
complex*16,dimension(6,6)::H,H_e,H1,H2,H2_inv,H_t,Id_,H_0

real*8,dimension(0:800020)::m_f_weight,m_field=0.d0
real*8,dimension(6,6)::mu_,energy_ !Dipole matrix elements (table3. page R188)
real*8,dimension(6)::sai_r,khy_r,ct_r
real*8::energy(6)! Excitation energys in atomic units (table2. page R187)

real*8::t,t_end,dt
real*8::alpha_k=0.2d0,pi=3.14159268d0
real*8::normm
!real*8::f_ft,f_potential,f_rp,f_teta
real*8::f_weight,yield,full_yield
integer*8::alloc,n,ErrorFlag,int_t

integer*8::exact_BVI,exact_BVF,exact_H0,exact_CT,exact_MU,exact_WE,exact_TR

complex*16::i=(0.d0,1.d0),t_sum,e_c

end